import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ClipboardList, Plus, RefreshCw, Save, Search, Trash2, Users, X } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { apiRequest, jsonBody } from '@/services/http';

type Student = { id: string; name: string; grade: string };
type Plan = { id?: string; grade: string; topic: string; notes?: string; weekStarting?: string; weekEnding?: string; updatedByName?: string };
type Parent = { id: string; name?: string; displayName?: string; email?: string; status?: string; identityHint?: string };
type Level = { id: string; name: string; description?: string; subjects: Subject[] };
type Subject = { id: string; name: string; chineseName?: string; englishName?: string; code?: string; isRequired?: boolean; topics?: Array<{ id: string; title: string }> };
type EnglishTask = { key: string; chineseName?: string; englishName?: string; displayName?: string; weeklyTargetCount: number; enabled: boolean; enabledFields: string[]; sortOrder: number };
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Request failed';
const sundayFor = (value: string) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() - date.getDay()); return date.toISOString().slice(0, 10); };
const today = new Date().toISOString().slice(0, 10);

export default function TeacherTools() {
  return <main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6"><div className="mb-6"><h1 className="text-2xl font-semibold">Teaching operations</h1><p className="text-sm text-muted-foreground">Weekly plans, completion records, English tasks, parent directory, and subject catalog</p></div><Tabs defaultValue="plans"><TabsList className="mb-5 h-auto w-full justify-start gap-1 overflow-x-auto bg-transparent p-0"><TabsTrigger value="plans">Grade plans</TabsTrigger><TabsTrigger value="records">Student completion</TabsTrigger><TabsTrigger value="english">English tasks</TabsTrigger><TabsTrigger value="parents">Parents</TabsTrigger><TabsTrigger value="subjects">Subject catalog</TabsTrigger></TabsList><TabsContent value="plans"><GradePlans /></TabsContent><TabsContent value="records"><PlanRecords /></TabsContent><TabsContent value="english"><StudentEnglishTasks /></TabsContent><TabsContent value="parents"><Parents /></TabsContent><TabsContent value="subjects"><SubjectCatalog /></TabsContent></Tabs></main>;
}

function GradePlans() {
  const [week, setWeek] = useState(sundayFor(today)); const [cycleEnd, setCycleEnd] = useState(''); const [rows, setRows] = useState<Plan[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [students, data] = await Promise.all([apiRequest<Student[]>('students'), apiRequest<{ cycle: { startDate: string; endDate: string }; plans: Plan[] }>(`grade-weekly-plans?weekStarting=${week}`)]); const grades = [...new Set(students.map((item) => item.grade).filter(Boolean))].sort(); const byGrade = new Map(data.plans.map((plan) => [plan.grade, plan])); setRows(grades.map((grade) => byGrade.get(grade) || { grade, topic: '', notes: '' })); setWeek(data.cycle.startDate); setCycleEnd(data.cycle.endDate); } catch (error) { toast.error(errorText(error)); } finally { setLoading(false); } }, [week]);
  useEffect(() => { void load(); }, []);
  const update = (grade: string, patch: Partial<Plan>) => setRows((current) => current.map((row) => row.grade === grade ? { ...row, ...patch } : row));
  const save = async (row: Plan) => { if (!row.topic.trim()) return toast.error('Plan topic is required'); setSaving(row.grade); try { const data = await apiRequest<{ plan: Plan }>('grade-weekly-plans', { method: 'POST', ...jsonBody({ grade: row.grade, weekStarting: week, weekEnding: cycleEnd, topic: row.topic, notes: row.notes || '' }) }); update(row.grade, data.plan); toast.success(`${row.grade} plan saved`); } catch (error) { toast.error(errorText(error)); } finally { setSaving(''); } };
  return <div><div className="mb-4 flex flex-wrap items-end gap-3"><div><Label>Week containing</Label><Input type="date" value={week} onChange={(event) => setWeek(sundayFor(event.target.value))} /></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Load week</Button><p className="pb-2 text-sm text-muted-foreground">{week} to {cycleEnd || '-'}</p></div><div className="grid gap-4 lg:grid-cols-2">{rows.map((row) => <Card key={row.grade}><CardHeader><CardTitle className="text-base">Grade {row.grade}</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>Plan topic</Label><Input value={row.topic} onChange={(event) => update(row.grade, { topic: event.target.value })} /></div><div><Label>Notes</Label><Textarea value={row.notes || ''} onChange={(event) => update(row.grade, { notes: event.target.value })} /></div><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{row.updatedByName ? `Last saved by ${row.updatedByName}` : 'No plan saved'}</p><Button size="sm" onClick={() => void save(row)} disabled={saving === row.grade}><Save className="mr-2 h-4 w-4" />Save</Button></div></CardContent></Card>)}</div>{!rows.length && <div className="py-12 text-center text-muted-foreground">No student grades found.</div>}</div>;
}

function PlanRecords() {
  const [students, setStudents] = useState<Student[]>([]); const [studentId, setStudentId] = useState(''); const [week, setWeek] = useState(sundayFor(today)); const [data, setData] = useState<{ plan: Plan | null; record: { score?: number; completed?: boolean; comment?: string } | null; cycle?: { startDate: string; endDate: string } } | null>(null); const [score, setScore] = useState(''); const [completed, setCompleted] = useState(true); const [comment, setComment] = useState('');
  useEffect(() => { apiRequest<Student[]>('students').then((rows) => { setStudents(rows); if (rows[0]) setStudentId(rows[0].id); }).catch((error) => toast.error(errorText(error))); }, []);
  const load = useCallback(async () => { if (!studentId) return; try { const result = await apiRequest<typeof data>(`students/${studentId}/weekly-plan-record?weekStarting=${week}`); setData(result); setWeek(result?.cycle?.startDate || week); setScore(result?.record?.score == null ? '' : String(result.record.score)); setCompleted(result?.record ? !!result.record.completed : true); setComment(result?.record?.comment || ''); } catch (error) { toast.error(errorText(error)); } }, [studentId, week]);
  useEffect(() => { void load(); }, [studentId]);
  const save = async () => { if (!data?.plan?.id) return toast.error('This grade does not have a plan for the selected week'); const numericScore = score === '' ? null : Number(score); if (numericScore != null && (numericScore < 0 || numericScore > 100)) return toast.error('Score must be between 0 and 100'); try { await apiRequest('student-weekly-plan-records', { method: 'POST', ...jsonBody({ studentId, gradeWeeklyPlanId: data.plan.id, score: numericScore, completed, comment }) }); toast.success('Completion record saved'); await load(); } catch (error) { toast.error(errorText(error)); } };
  return <div className="grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><Card><CardContent className="space-y-4 p-5"><div><Label>Student</Label><Select value={studentId} onValueChange={setStudentId}><SelectTrigger><SelectValue placeholder="Select student" /></SelectTrigger><SelectContent>{students.map((student) => <SelectItem key={student.id} value={student.id}>{student.name} · {student.grade}</SelectItem>)}</SelectContent></Select></div><div><Label>Week containing</Label><Input type="date" value={week} onChange={(event) => setWeek(sundayFor(event.target.value))} /></div><Button variant="outline" className="w-full" onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" />Load</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base">{data?.plan ? `${data.plan.grade}: ${data.plan.topic}` : 'No grade plan'}</CardTitle></CardHeader><CardContent className="space-y-4">{data?.plan ? <><p className="text-sm text-muted-foreground">{data.plan.notes || 'No plan notes'}</p><div><Label>Score (0-100)</Label><Input type="number" min={0} max={100} value={score} onChange={(event) => setScore(event.target.value)} /></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={completed} onCheckedChange={(value) => setCompleted(value === true)} />Completed</label><div><Label>Teacher comment</Label><Textarea value={comment} onChange={(event) => setComment(event.target.value)} /></div><Button onClick={() => void save()}><CheckCircle2 className="mr-2 h-4 w-4" />Save completion</Button></> : <p className="text-sm text-muted-foreground">Create the grade plan first, then record this student's completion.</p>}</CardContent></Card></div>;
}

function Parents() {
  const [parents, setParents] = useState<Parent[]>([]); const [query, setQuery] = useState(''); const [bindings, setBindings] = useState<Record<string, Student[]>>({});
  const load = useCallback(async () => { try { setParents(await apiRequest<Parent[]>('parents')); } catch (error) { toast.error(errorText(error)); } }, []); useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => parents.filter((parent) => `${parent.displayName || parent.name || ''} ${parent.email || ''} ${parent.identityHint || ''}`.toLowerCase().includes(query.toLowerCase())), [parents, query]);
  const toggle = async (id: string) => { if (bindings[id]) return setBindings((value) => { const next = { ...value }; delete next[id]; return next; }); try { const rows = await apiRequest<Student[]>(`parents/${id}/students`); setBindings((value) => ({ ...value, [id]: rows })); } catch (error) { toast.error(errorText(error)); } };
  const remove = async (id: string) => { try { const rows = bindings[id] || await apiRequest<Student[]>(`parents/${id}/students`); if (rows.length) return toast.error('Unbind this parent from all students before deleting the account'); if (!confirm('Permanently delete this parent account?')) return; await apiRequest(`parents/${id}`, { method: 'DELETE' }); toast.success('Parent deleted'); await load(); } catch (error) { toast.error(errorText(error)); } };
  return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5" />Parent directory</CardTitle><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="w-64 pl-9" placeholder="Search parents" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div></CardHeader><CardContent><div className="divide-y">{filtered.map((parent) => <div key={parent.id} className="py-4"><div className="flex flex-wrap items-center gap-3"><div className="min-w-0 flex-1"><p className="font-medium">{parent.displayName || parent.name || 'Unnamed parent'}</p><p className="text-xs text-muted-foreground">{parent.email || parent.identityHint || 'WeChat account'} · {parent.status || 'approved'}</p></div><Button variant="outline" size="sm" onClick={() => void toggle(parent.id)}>Students</Button><Button variant="ghost" size="icon" onClick={() => void remove(parent.id)} aria-label="Delete parent"><Trash2 className="h-4 w-4" /></Button></div>{bindings[parent.id] && <div className="mt-3 flex flex-wrap gap-2">{bindings[parent.id].length ? bindings[parent.id].map((student) => <span key={student.id} className="border px-2 py-1 text-xs">{student.name} · {student.grade}</span>) : <span className="text-xs text-muted-foreground">No students bound</span>}</div>}</div>)}</div></CardContent></Card>;
}

function StudentEnglishTasks() {
  const [students, setStudents] = useState<Student[]>([]); const [studentId, setStudentId] = useState(''); const [tasks, setTasks] = useState<EnglishTask[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { apiRequest<Student[]>('students').then((rows) => { setStudents(rows); if (rows[0]) setStudentId(rows[0].id); }).catch((error) => toast.error(errorText(error))); }, []);
  const load = useCallback(async () => { if (!studentId) return; setLoading(true); try { const data = await apiRequest<{ tasks: EnglishTask[] }>(`students/${studentId}/english-tasks`); setTasks(data.tasks || []); } catch (error) { toast.error(errorText(error)); } finally { setLoading(false); } }, [studentId]);
  useEffect(() => { void load(); }, [studentId]);
  const update = (index: number, patch: Partial<EnglishTask>) => setTasks((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const save = async () => { try { const data = await apiRequest<{ tasks: EnglishTask[] }>(`students/${studentId}/english-tasks`, { method: 'PUT', ...jsonBody({ tasks: tasks.map((task, index) => ({ ...task, sortOrder: index })) }) }); setTasks(data.tasks); toast.success('Student English tasks saved'); } catch (error) { toast.error(errorText(error)); } };
  const reset = async () => { if (!confirm('Reset this student to the global English task configuration?')) return; try { const data = await apiRequest<{ tasks: EnglishTask[] }>(`students/${studentId}/english-tasks/reset`, { method: 'POST' }); setTasks(data.tasks); toast.success('English tasks reset'); } catch (error) { toast.error(errorText(error)); } };
  return <div className="space-y-4"><Card><CardContent className="flex flex-wrap items-end gap-3 p-5"><div className="min-w-64 flex-1"><Label>Student</Label><Select value={studentId} onValueChange={setStudentId}><SelectTrigger><SelectValue placeholder="Select student" /></SelectTrigger><SelectContent>{students.map((student) => <SelectItem key={student.id} value={student.id}>{student.name} · {student.grade}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</Button><Button variant="outline" onClick={() => void reset()}>Reset defaults</Button><Button onClick={() => void save()}><Save className="mr-2 h-4 w-4" />Save tasks</Button></CardContent></Card><Card><CardContent className="space-y-3 p-5">{tasks.map((task, index) => <div key={task.key} className="grid items-center gap-2 border p-3 sm:grid-cols-[auto_1fr_1fr_120px_auto]"><Checkbox checked={task.enabled} onCheckedChange={(value) => update(index, { enabled: value === true })} /><Input value={task.chineseName || ''} placeholder="Chinese name" onChange={(event) => update(index, { chineseName: event.target.value })} /><Input value={task.englishName || ''} placeholder="English name" onChange={(event) => update(index, { englishName: event.target.value })} /><Input type="number" min={0} max={500} value={task.weeklyTargetCount} onChange={(event) => update(index, { weeklyTargetCount: Number(event.target.value) })} /><Button variant="ghost" size="icon" onClick={() => setTasks((rows) => rows.filter((_, rowIndex) => rowIndex !== index))} aria-label="Remove English task"><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card></div>;
}

function SubjectCatalog() {
  const [levels, setLevels] = useState<Level[]>([]); const [newLevel, setNewLevel] = useState(''); const [drafts, setDrafts] = useState<Record<string, { chineseName: string; englishName: string; code: string }>>({});
  const load = useCallback(async () => { try { const data = await apiRequest<{ levels: Level[] }>('subjects/hierarchy'); setLevels(data.levels || []); } catch (error) { toast.error(errorText(error)); } }, []); useEffect(() => { void load(); }, [load]);
  const addLevel = async () => { if (!newLevel.trim()) return; try { await apiRequest('subject-levels', { method: 'POST', ...jsonBody({ name: newLevel.trim() }) }); setNewLevel(''); toast.success('Level added'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const addSubject = async (levelId: string) => { const form = drafts[levelId]; if (!form?.chineseName.trim() && !form?.englishName.trim()) return toast.error('Enter a subject name'); const name = form.chineseName.trim() || form.englishName.trim(); const code = (form.code || form.englishName || name).toUpperCase().replace(/[^A-Z0-9]+/g, '_'); try { await apiRequest('subjects', { method: 'POST', ...jsonBody({ levelId, name, chineseName: form.chineseName, englishName: form.englishName, code, isRequired: false, sortOrder: 0, isActive: true }) }); setDrafts((value) => ({ ...value, [levelId]: { chineseName: '', englishName: '', code: '' } })); toast.success('Subject added'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const addTopic = async (subjectId: string) => { const title = prompt('Topic name'); if (!title?.trim()) return; const code = title.toUpperCase().replace(/[^A-Z0-9]+/g, '_'); try { await apiRequest(`subjects/${subjectId}/topics`, { method: 'POST', ...jsonBody({ code, title: title.trim(), orderIndex: code, parentTopicId: null }) }); toast.success('Topic added'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const editLevel = async (level: Level) => { const name = prompt('Level name', level.name); if (!name?.trim()) return; try { await apiRequest(`subject-levels/${level.id}`, { method: 'PUT', ...jsonBody({ name: name.trim(), description: level.description || '', sortOrder: 0, isActive: true }) }); toast.success('Level updated'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const deleteLevel = async (level: Level) => { if (!confirm(`Delete empty level ${level.name}?`)) return; try { await apiRequest(`subject-levels/${level.id}`, { method: 'DELETE' }); toast.success('Level deleted'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const editSubject = async (subject: Subject, levelId: string) => { const name = prompt('Subject name', subject.chineseName || subject.name); if (!name?.trim()) return; try { await apiRequest(`subjects/${subject.id}`, { method: 'PUT', ...jsonBody({ levelId, name: name.trim(), chineseName: name.trim(), englishName: subject.englishName || '', code: subject.code || name.toUpperCase().replace(/[^A-Z0-9]+/g, '_'), isRequired: !!subject.isRequired, sortOrder: 0, isActive: true }) }); toast.success('Subject updated'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const deleteSubject = async (subject: Subject) => { if (!confirm(`Delete ${subject.name} from the catalog?`)) return; try { await apiRequest(`subjects/${subject.id}`, { method: 'DELETE' }); toast.success('Subject deleted'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const editTopic = async (subjectId: string, topic: { id: string; title: string }) => { const title = prompt('Topic name', topic.title); if (!title?.trim()) return; const code = title.toUpperCase().replace(/[^A-Z0-9]+/g, '_'); try { await apiRequest(`topics/${topic.id}`, { method: 'PUT', ...jsonBody({ code, title: title.trim(), orderIndex: code, parentTopicId: null, subjectId }) }); toast.success('Topic updated'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const deleteTopic = async (topic: { id: string; title: string }) => { if (!confirm(`Delete topic ${topic.title}?`)) return; try { await apiRequest(`topics/${topic.id}`, { method: 'DELETE' }); toast.success('Topic deleted'); await load(); } catch (error) { toast.error(errorText(error)); } };
  return <div><div className="mb-5 flex max-w-md gap-2"><Input placeholder="New level, e.g. Sec 1" value={newLevel} onChange={(event) => setNewLevel(event.target.value)} /><Button onClick={() => void addLevel()}><Plus className="mr-2 h-4 w-4" />Level</Button></div><div className="space-y-5">{levels.map((level) => { const draft = drafts[level.id] || { chineseName: '', englishName: '', code: '' }; return <Card key={level.id}><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">{level.name}</CardTitle><div className="flex"><Button variant="ghost" size="icon" onClick={() => void editLevel(level)} aria-label="Edit level"><ClipboardList className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => void deleteLevel(level)} aria-label="Delete level"><Trash2 className="h-4 w-4" /></Button></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 lg:grid-cols-2">{level.subjects.map((subject) => <div key={subject.id} className="border p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{subject.chineseName || subject.name}{subject.englishName ? ` (${subject.englishName})` : ''}</p><p className="text-xs text-muted-foreground">{subject.code}{subject.isRequired ? ' · Required' : ''}</p></div><div className="flex"><Button variant="ghost" size="icon" onClick={() => void editSubject(subject, level.id)} aria-label="Edit subject"><ClipboardList className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => void deleteSubject(subject)} aria-label="Delete subject"><Trash2 className="h-4 w-4" /></Button><Button variant="outline" size="sm" onClick={() => void addTopic(subject.id)}><Plus className="mr-1 h-3 w-3" />Topic</Button></div></div>{subject.topics?.length ? <div className="mt-3 flex flex-wrap gap-1">{subject.topics.map((topic) => <span key={topic.id} className="inline-flex items-center gap-1 bg-muted px-2 py-1 text-xs"><button onClick={() => void editTopic(subject.id, topic)}>{topic.title}</button><button onClick={() => void deleteTopic(topic)} aria-label={`Delete ${topic.title}`}><X className="h-3 w-3" /></button></span>)}</div> : null}</div>)}</div><div className="grid gap-2 border-t pt-4 sm:grid-cols-[1fr_1fr_140px_auto]"><Input placeholder="Chinese name" value={draft.chineseName} onChange={(event) => setDrafts({ ...drafts, [level.id]: { ...draft, chineseName: event.target.value } })} /><Input placeholder="English name" value={draft.englishName} onChange={(event) => setDrafts({ ...drafts, [level.id]: { ...draft, englishName: event.target.value } })} /><Input placeholder="Code" value={draft.code} onChange={(event) => setDrafts({ ...drafts, [level.id]: { ...draft, code: event.target.value } })} /><Button variant="outline" onClick={() => void addSubject(level.id)}><Plus className="mr-2 h-4 w-4" />Subject</Button></div></CardContent></Card>; })}</div></div>;
}
