import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, Download, LogOut, RefreshCw, Save, Search, Settings2, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { apiRequest, downloadAuthenticated, jsonBody } from '@/services/http';

type Pending = { id: string; role: 'teacher' | 'parent'; displayName?: string; name?: string; email?: string; wechatOpenIdMasked?: string };
type UserGroup = { identityKey: string; displayName: string; roles: Array<{ id: string; role: string; email?: string }> };
type ReviewItem = { id: string; type: string; typeLabel?: string; studentName?: string; title: string; summary?: string; updatedByName?: string; updatedAt?: string };
type Task = { key: string; chineseName?: string; englishName?: string; displayName?: string; weeklyTargetCount: number; enabled: boolean; enabledFields: string[]; sortOrder: number };
const today = new Date().toISOString().slice(0, 10);
const sundayFor = (value: string) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() - date.getDay()); return date.toISOString().slice(0, 10); };
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Request failed';

export default function AdminConsole() {
  const navigate = useNavigate();
  const logout = () => { localStorage.removeItem('adminToken'); localStorage.removeItem('edunet-token'); navigate('/admin/login'); };
  return <main className="min-h-screen bg-background"><header className="border-b bg-card"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><ShieldCheck className="h-5 w-5 text-primary" /><div className="flex-1"><p className="font-semibold">EduNet admin console</p><p className="text-xs text-muted-foreground">Production review and system operations</p></div><Button variant="ghost" size="sm" onClick={logout}><LogOut className="mr-2 h-4 w-4" />Log out</Button></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><Tabs defaultValue="review"><TabsList className="mb-5 h-auto w-full justify-start gap-1 overflow-x-auto bg-transparent p-0"><TabsTrigger value="review">Review queue</TabsTrigger><TabsTrigger value="users">Users</TabsTrigger><TabsTrigger value="plans">Plan reports</TabsTrigger><TabsTrigger value="settings">Configuration</TabsTrigger><TabsTrigger value="students" onClick={() => navigate('/admin/dashboard')}>Student data</TabsTrigger></TabsList><TabsContent value="review"><ReviewQueue /></TabsContent><TabsContent value="users"><UserManagement /></TabsContent><TabsContent value="plans"><PlanReports /></TabsContent><TabsContent value="settings"><SystemSettings /></TabsContent></Tabs></div></main>;
}

function ReviewQueue() {
  const [items, setItems] = useState<ReviewItem[]>([]); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const data = await apiRequest<{ pending: ReviewItem[] }>('admin/feedback-review'); setItems(data.pending || []); } catch (error) { toast.error(errorText(error)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const act = async (item: ReviewItem, publish: boolean) => { if (!publish && !confirm('Delete this submission from the review queue?')) return; try { await apiRequest(`admin/feedback-review/${item.type}/${item.id}${publish ? '/publish' : ''}`, { method: publish ? 'POST' : 'DELETE' }); toast.success(publish ? 'Published to parents' : 'Submission deleted'); await load(); } catch (error) { toast.error(errorText(error)); } };
  return <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Pending feedback and reports ({items.length})</CardTitle><Button variant="outline" size="icon" onClick={() => void load()} aria-label="Refresh"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></Button></div></CardHeader><CardContent>{items.length ? <div className="divide-y">{items.map((item) => <div key={`${item.type}-${item.id}`} className="py-5"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{item.typeLabel || item.type}</Badge><p className="font-medium">{item.studentName} · {item.title}</p></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm text-muted-foreground">{item.summary || 'No summary text'}</p><p className="mt-2 text-xs text-muted-foreground">Submitted by {item.updatedByName || 'Unknown'} · {String(item.updatedAt || '').slice(0, 16).replace('T', ' ')}</p></div><Button size="sm" onClick={() => void act(item, true)}><Check className="mr-2 h-4 w-4" />Publish</Button><Button variant="outline" size="sm" onClick={() => void act(item, false)}><Trash2 className="mr-2 h-4 w-4" />Delete</Button></div></div>)}</div> : <div className="py-12 text-center text-muted-foreground">The review queue is clear.</div>}</CardContent></Card>;
}

function UserManagement() {
  const [users, setUsers] = useState<UserGroup[]>([]); const [pending, setPending] = useState<Pending[]>([]); const [query, setQuery] = useState('');
  const load = useCallback(async () => { try { const [groups, waiting] = await Promise.all([apiRequest<{ users: UserGroup[] }>('admin/users'), apiRequest<{ teachers: Pending[]; parents: Pending[] }>('admin/pending')]); setUsers(groups.users || []); setPending([...(waiting.teachers || []).map((item) => ({ ...item, role: 'teacher' as const })), ...(waiting.parents || []).map((item) => ({ ...item, role: 'parent' as const }))]); } catch (error) { toast.error(errorText(error)); } }, []); useEffect(() => { void load(); }, [load]);
  const decide = async (item: Pending, approve: boolean) => { if (!approve && !confirm('Reject this account request?')) return; try { await apiRequest(`admin/${approve ? 'approve' : 'reject'}`, { method: 'POST', ...jsonBody({ id: item.id, role: item.role }) }); toast.success(approve ? 'Account approved' : 'Account rejected'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const edit = async (group: UserGroup) => { const primary = group.roles[0]; if (!primary) return; const displayName = prompt('Display name', group.displayName); if (!displayName?.trim()) return; const value = prompt('Roles (comma-separated: admin, teacher, parent)', group.roles.map((role) => role.role).join(', ')); if (!value) return; const roles = value.split(',').map((role) => role.trim().toLowerCase()).filter((role) => ['admin', 'teacher', 'parent'].includes(role)); if (!roles.length) return toast.error('At least one valid role is required'); try { await apiRequest('admin/users/set-roles', { method: 'POST', ...jsonBody({ sourceRole: primary.role, sourceId: primary.id, displayName: displayName.trim(), roles }) }); toast.success('User updated'); await load(); } catch (error) { toast.error(errorText(error)); } };
  const filtered = useMemo(() => users.filter((user) => `${user.displayName} ${user.roles.map((role) => role.role).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  return <div className="space-y-5">{pending.length > 0 && <Card><CardHeader><CardTitle>Pending account requests ({pending.length})</CardTitle></CardHeader><CardContent><div className="divide-y">{pending.map((item) => <div key={`${item.role}-${item.id}`} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="font-medium">{item.displayName || item.name || 'Unnamed user'}</p><p className="text-xs text-muted-foreground">{item.role} · {item.email || item.wechatOpenIdMasked || 'WeChat identity'}</p></div><Button size="sm" onClick={() => void decide(item, true)}><Check className="mr-1 h-4 w-4" />Approve</Button><Button variant="outline" size="sm" onClick={() => void decide(item, false)}><X className="mr-1 h-4 w-4" />Reject</Button></div>)}</div></CardContent></Card>}<Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5" />Active users</CardTitle><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="w-64 pl-9" placeholder="Search users" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div></CardHeader><CardContent><div className="divide-y">{filtered.map((group) => <button key={group.identityKey} className="flex w-full items-center gap-3 py-4 text-left hover:bg-muted/50" onClick={() => void edit(group)}><div className="min-w-0 flex-1"><p className="font-medium">{group.displayName}</p><p className="text-xs text-muted-foreground">{group.roles.map((role) => role.email).filter(Boolean)[0] || 'WeChat identity'}</p></div><div className="flex gap-1">{group.roles.map((role) => <Badge key={`${role.role}-${role.id}`} variant="outline">{role.role}</Badge>)}</div></button>)}</div></CardContent></Card></div>;
}

function PlanReports() {
  const [week, setWeek] = useState(sundayFor(today)); const [start, setStart] = useState(`${today.slice(0, 4)}-01-01`); const [end, setEnd] = useState(today); const [groups, setGroups] = useState<Array<{ grade: string; plan?: { topic?: string }; rows?: Array<{ studentName?: string; name?: string; score?: number; completed?: boolean }> }>>([]); const [metrics, setMetrics] = useState<Record<string, number>>({});
  const loadWeekly = async () => { try { const data = await apiRequest<{ groups: typeof groups; metrics: Record<string, number> }>(`admin/weekly-plan-summary?weekStarting=${week}`); setGroups(data.groups || []); setMetrics(data.metrics || {}); } catch (error) { toast.error(errorText(error)); } }; useEffect(() => { void loadWeekly(); }, []);
  const exportFile = async (kind: 'weekly' | 'term' | 'tasks') => { try { const endpoint = kind === 'weekly' ? `admin/weekly-plan-summary/export?weekStarting=${week}` : kind === 'term' ? `admin/term-plan-summary/export?startDate=${start}&endDate=${end}` : `admin/learning-task-completion/export?startDate=${start}&endDate=${end}`; await downloadAuthenticated(endpoint, `${kind}-report-${kind === 'weekly' ? week : `${start}-${end}`}.xlsx`); } catch (error) { toast.error(errorText(error)); } };
  return <div className="space-y-5"><Card><CardContent className="flex flex-wrap items-end gap-3 p-5"><div><Label>Weekly report</Label><Input type="date" value={week} onChange={(event) => setWeek(sundayFor(event.target.value))} /></div><Button variant="outline" onClick={() => void loadWeekly()}><RefreshCw className="mr-2 h-4 w-4" />Load</Button><Button onClick={() => void exportFile('weekly')}><Download className="mr-2 h-4 w-4" />Export weekly</Button><div className="hidden h-10 w-px bg-border sm:block" /><div><Label>Term start</Label><Input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></div><div><Label>Term end</Label><Input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></div><Button variant="outline" onClick={() => void exportFile('term')}><Download className="mr-2 h-4 w-4" />Term summary</Button><Button variant="outline" onClick={() => void exportFile('tasks')}><Download className="mr-2 h-4 w-4" />Learning tasks</Button></CardContent></Card><div className="grid gap-3 sm:grid-cols-3">{Object.entries(metrics).slice(0, 6).map(([key, value]) => <div key={key} className="border bg-card p-4"><p className="text-xs capitalize text-muted-foreground">{key.replace(/([A-Z])/g, ' $1')}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2">{groups.map((group) => <Card key={group.grade}><CardHeader><CardTitle className="text-base">Grade {group.grade} · {group.plan?.topic || 'No plan'}</CardTitle></CardHeader><CardContent><div className="divide-y">{(group.rows || []).map((row, index) => <div key={`${row.studentName || row.name}-${index}`} className="flex items-center justify-between py-2 text-sm"><span>{row.studentName || row.name}</span><span className={row.completed ? 'text-emerald-600' : 'text-muted-foreground'}>{row.score ?? '-'} · {row.completed ? 'Complete' : 'Incomplete'}</span></div>)}</div></CardContent></Card>)}</div></div>;
}

function SystemSettings() {
  const [tasks, setTasks] = useState<Task[]>([]); const [study, setStudy] = useState({ enabled: true, days: [0,1,2,3,4], startTime: '18:00', endTime: '21:00' });
  const load = useCallback(async () => { try { const [taskData, studyData] = await Promise.all([apiRequest<{ tasks: Task[] }>('admin/english-tasks'), apiRequest<typeof study>('study-settings')]); setTasks(taskData.tasks || []); setStudy(studyData); } catch (error) { toast.error(errorText(error)); } }, []); useEffect(() => { void load(); }, [load]);
  const updateTask = (index: number, patch: Partial<Task>) => setTasks((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const saveTasks = async () => { try { const data = await apiRequest<{ tasks: Task[] }>('admin/english-tasks', { method: 'PUT', ...jsonBody({ tasks: tasks.map((task, index) => ({ ...task, sortOrder: index })) }) }); setTasks(data.tasks); toast.success('English tasks saved'); } catch (error) { toast.error(errorText(error)); } };
  const saveStudy = async () => { try { setStudy(await apiRequest<typeof study>('admin/study-settings', { method: 'PUT', ...jsonBody(study) })); toast.success('Study schedule saved'); } catch (error) { toast.error(errorText(error)); } };
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Global English tasks</CardTitle><Button onClick={() => void saveTasks()}><Save className="mr-2 h-4 w-4" />Save tasks</Button></div></CardHeader><CardContent className="space-y-3">{tasks.map((task, index) => <div key={task.key} className="grid items-center gap-2 border p-3 sm:grid-cols-[auto_1fr_1fr_110px_auto]"><Checkbox checked={task.enabled} onCheckedChange={(value) => updateTask(index, { enabled: value === true })} /><Input value={task.chineseName || ''} placeholder="Chinese name" onChange={(event) => updateTask(index, { chineseName: event.target.value })} /><Input value={task.englishName || ''} placeholder="English name" onChange={(event) => updateTask(index, { englishName: event.target.value })} /><Input type="number" min={0} max={500} value={task.weeklyTargetCount} onChange={(event) => updateTask(index, { weeklyTargetCount: Number(event.target.value) })} /><Button variant="ghost" size="icon" onClick={() => setTasks((rows) => rows.filter((_, rowIndex) => rowIndex !== index))} aria-label="Remove task"><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card><Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="h-5 w-5" />Evening study schedule</CardTitle></CardHeader><CardContent className="space-y-4"><label className="flex items-center gap-2 text-sm"><Checkbox checked={study.enabled} onCheckedChange={(value) => setStudy({ ...study, enabled: value === true })} />Enabled</label><div className="grid grid-cols-2 gap-3"><div><Label>Start</Label><Input type="time" value={study.startTime} onChange={(event) => setStudy({ ...study, startTime: event.target.value })} /></div><div><Label>End</Label><Input type="time" value={study.endTime} onChange={(event) => setStudy({ ...study, endTime: event.target.value })} /></div></div><div><Label>Active days</Label><div className="mt-2 grid grid-cols-4 gap-2">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((label, day) => <Button key={label} type="button" size="sm" variant={study.days.includes(day) ? 'default' : 'outline'} onClick={() => setStudy({ ...study, days: study.days.includes(day) ? study.days.filter((value) => value !== day) : [...study.days, day].sort() })}>{label}</Button>)}</div></div><Button className="w-full" onClick={() => void saveStudy()}><Save className="mr-2 h-4 w-4" />Save schedule</Button></CardContent></Card></div>;
}
